env:
  global:
    - PROJECT_NAME="cu2qu"
    - PROJECT_VERSION="1.6.7"
    - BUILD_DEPENDS="cython"
    - PLAT=x86_64
    - UNICODE_WIDTH=32
    - TWINE_USERNAME="anthrotype"
    - secure: JM0mnZrtWWc1e1ujsZPzLg+1aiSMM1dDYY41yyjGT1VLt839QspcCtq0LoRKudhQ29x5PgP8spCzZYp5EioEqh5lkd4m5ymfRdyrp2TnL74QWDJsTpx57qOjwpIyWM+PubXrzcns1TjVTK1gcyg2TqsbWrhKT7ZLpH0YhyH1f3UUdkuzYcGEsNeu4JXwY6qPrf+ypoyB8WFnd3y3v/vsd4mi+XWuoUQ5Q19UeJ7iv7s6ghRDD75EHqadw3yywYdVYOGtjWxu+VEhrLciMhjovaAFJKPcIHtfScmtK/mHeORuRBGDnsWvYNHXXXnxCqyEy/YohwAtMt8RsGe0jRPu8RamJXUqIdvbJPaTscVAsG7QSNWoSXSGeGbTDFVyXcTLTkHWw8CXf54J14GZbCRmuxJZ0PTRpdb9h3vJ+AQ/nWRZm4hSM3PwOja4O5wi6rKOaefMbXlnuaBd6XiI7xql9rbGTtYNVL1rAfiqK9G04TuNQXhJxibn8LOO9LWdEsl9SdH/2BrltNHuWWiM6RvS2evf/shitAgd4uiJ7pFZKNlEpR+YFP8Tcstw4oWd/GDHLOkgRmJbMBWx6bo/AqakUQ7lLbTpKcRKB5jS34ByfAuuQdvS04k2NigFiCyLZLjHd284TSUqhrzVBRwZ1dRuYkAP8CeCeHExSaz3A+luAH0=

# The following prevents Travis from running CI on pull requests that come from a
# branch in the same repository. Without this, it will run the same CI for the
# pull request branch _and_ the pull request itself, which makes no sense.
branches:
  only:
    - master
    # We want to build wip/* branches since these are not usually used for PRs
    - /^wip\/.*$/
    # We want to build version tags as well.
    - /^v\d+\.\d+.*$/

language: generic
dist: xenial
services: docker

matrix:
  include:
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - BUILD_SDIST=true
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
        - PLAT=i686
    - os: osx
      env:
        - MB_PYTHON_VERSION=2.7
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.6
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.7
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.8

before_install:
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install

install:
  - build_index_wheel "${PROJECT_NAME}==${PROJECT_VERSION}"

script:
  - install_run $PLAT

after_success:
  - |
    if [ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_REPO_SLUG" == "anthrotype/cu2qu-wheels" ]; then
      pip install --upgrade twine
      twine upload wheelhouse/*.whl
    fi
